### PR TITLE
Adding detail to the README current->v1.9

### PR DESCRIPTION
**Pull request by DavidLiedle**
This was accepted into master; rolling up to v1.9 as well

### CODE REVIEW

**Comment by andrerom** [comment]
Shouldn't you rather merge master into v1.9 to forward port changes?

**Comment by DavidLiedle** [comment]
@andrerom As you say, this merges master into v1.9 to forward-port the changes.

>	DavidLiedle  wants to merge 1 commit into v1.9 from master

**Comment by DavidLiedle** [comment]
This is a unique case, in which I altered the current-recommended product requirements (README) in master first. Normally changes will roll in from the "top" down, but I need to do a bit of final cleanup so I went bottom-up.

**Comment by andrerom** [comment]
> Normally changes will roll in from the "top" down, but I need to do a bit of final cleanup so I went bottom-up.

well, there probably will be some fixes on files in master that don't change behaviour / requirements.

**Comment by DavidLiedle** [comment]
@andrerom yes, and those can be rolled up exactly like they are in this instance.

**Pull request merged**
