### PR TITLE
[v2] Docker, Deployment and Migration

### PR DESCRIPTION
**Pull request by andrerom**
Related epics:
- https://jira.ez.no/browse/EZP-25665
- https://jira.ez.no/browse/EZP-26310
- https://jira.ez.no/browse/EZP-25865
- (...)

Closes https://github.com/ezsystems/specs/pull/28
Closes #5

### CODE REVIEW

**Comment by rolandbenedetti** [comment]
Hello guys,

I'm glad you took this meeting to clarify a bit this topic. I have a few comments reading this new requirement document.
First to me, it's less concrete and much more abstract than the two previous requirements that Bard wrote (https://github.com/ezsystems/specs/blob/ec1a1b38b4fd94a02b51932b29fcbf6632279b7f/DX/Docker/Requirements_repo_init.md and  https://github.com/ezsystems/specs/blob/ec1a1b38b4fd94a02b51932b29fcbf6632279b7f/DX/Docker/Requirements_dev_replicate.md ). Is it replacing those requirements?
It might be because I am not technical enough but I tend to think requirements should be clear to me  and other non technical people (which is not the case of specifications).

My questions that I'd love to have answers on:
- What is a "a best practice blueprint for server environment "? Is it documentation? configuration? tool? In previous requirements, we said sthg like "as a developer, I want to have a command line that will install eZ having docker running under the hood". This was way clearer to me.
- Another comment is that I am not sure to get the milestones.
- In M2, is that I have the impression we are trying to support natively plenty of cloud IaaS providers, is that too ambitious? 
- In general, I think the previous requirements where focusing on developer environments on purpose and I am somehow thinking it was better to narrow the initial scope. I am a bit concerned we are here trying to do the universal overly generic deployment feature.

Happy to read answers, I'd also be happy to better understand the next steps here.

**Comment by andrerom** [comment]
Server environment blueprint is a set of:
- docker containers, some from us, some from official docker hub repositories
- docker compose config to serve as example
- documentation on how to use it

Effectively it aims to be best practice server setup with examples for all options. 

So for instance we might have a package contianing a set of these, and on installation use this to generate DockerFile and docker-compose config _(for dev and prod)_ they will need for getting up and running. This way they can adjust it to their needs without conflicting with changes we do to the blue prints.

**Comment by rolandbenedetti** [comment]
Thanks André,

More comments and answers:

> Effectively it aims to be best practice server setup with examples for all options.

Thanks for the explanation. 
I'm still wondering if, at the end, the developer lambda as I am has access to a super simple install of a developer environment? 
Like I did when trying Sebastien's work. His scripts clearly needed testing, but it was cool to have in 10 minute a full stack running on my Mac. Because that's the requirement at the end of the day.

Is that part of the requirement? It's a bit unclear to me.

> To your question: I think we all agree we should split them up in three (simpler) requirements.

I confirm I agree. I'm better with different requirements here :-)

**Comment by andrerom** [comment]
> Is that part of the requriment?

Yes it should be, suggested wording?

**Comment by rolandbenedetti** [comment]
> suggested wording?

Provide developers with tooling (e.g. scripts, commands, application) that simplify the creation of a developer environment (initial environment, or environment for an existing project codebase), removing the complexity of the underlying infrastructure such as Docker. This tooling would not have to be certified as eZ Platform software, and could be provided outside of any guarantee.

**Pull request merged**
